obj-y += libfdt/fdt_addresses.o libfdt/fdt.o libfdt/fdt_check.o libfdt/fdt_empty_tree.o libfdt/fdt_overlay.o
obj-y += libfdt/fdt_ro.o libfdt/fdt_rw.o libfdt/fdt_strerror.o libfdt/fdt_sw.o libfdt/fdt_wip.o
obj-y += libfdt/tool_func.o